trainer:
  train_epochs: 60
  progress_bar_refresh_rate: 1
  gpus: 1
  fine_tuning: false
  model_name: ""
  use_gpu: true

watermark:
  seed: 42
  ldpc_seed: 8
  parameter_seed: 43
  ratio: 0.00125
  error_correction: true
  embed_path: "marks/mark.txt"
  extract_path: "marks/extract/"
  start: 1
  end: 2
  gamma: 0.0009

hydra:
  run:
    dir: outputs/${dataset.name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

removal:
  prune: false
  prune_ratio: 0.1

defaults:
  - _self_
  - dataset: gtsrb
  - model: vgg
